### ISSUE TITLE
Add missing appimages

### ISSUE THREAD

**Issue by danrobi11** [app-outlet/app-outlet#108]
Hello. First time trying app-outlet. Pretty neat idea. I havent found any contact info or IRC/Discord so im opening an issue.
I was wondering where app-outlet was searching for appimages. From what I've read in #70 it seems like the list is hosted on your server, correct? Or does it search from https://appimage.github.io
Anyhow, these appimages could be added:
- [BeakerBrowser](https://github.com/beakerbrowser/beaker/)
- [MuWire](https://github.com/zlatinb/muwire/)
- [LibreWolf](https://gitlab.com/librewolf-community/browser/linux)
- [sc-controller](https://github.com/kozec/sc-controller/)

**Comment by MessiasLima** [comment]
Hello @danrobi11 . I'm sorry for the delayed response. 

We search the apps on https://appimage.github.io/. We maintain a database of applications but only for performance purposes.

3 of the 4 applications are available on AppOutlet. 

MuWire is available on https://appimage.github.io/ but does not appear on AppOutlet. This is due there is no Download link provided by the developers. 

In order to fix this and the applications start to appear on AppOutlet, please ask the developers to fix this problem with https://appimage.github.io/

Thank you for your support
