### ISSUE TITLE
Create Flatpak package

### ISSUE THREAD

**Issue by MessiasLima** [app-outlet/app-outlet#32]
Analyze the possibility of creating `flatpak` package from electron project or from the linux-unpacked folder (generated in the current build process).

**Comment by sudo-give-me-coffee** [comment]
By the way that flatpak works, is impossible generate a software centre with this format, the following limitations not allow it (is caused by :

* The following limitations do not allow:
Read-only file system

* Demand hacks to access the real file system

* Is impossible get root access level (UID=0), this is needed to write access on /var to install snaps (and flatpaks globaly)

* Can't use flatpak inside itself

* And other minor things... 

You can close safety this issue because is impossible do this

**Comment by MessiasLima** [comment]
Thanks.
